kind: pipeline
name: synbak

environment:
  APP_VER: 3.8.0

trigger:
  event:
  - push
  branch:
  - master

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: izdock/devtoolset-7-toolchain-centos7
  commands:
  - ./autogen.sh
  - ./configure
  - make release

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: web01
    port: 22
    username:
      from_secret: USERNAME
    password:
      from_secret: PASSWORD
    source: release/synbak-${APP_VER}-1.noarch.rpm
    target: /var/www/virtual/repo.initzero.it/centos/8/RPMS/noarch
