kind: pipeline
name: synbak

environment:
  APP_VER: 3.8.0

trigger:
  event:
  - push
  branch:
  - master

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: izdock/devtoolset-7-toolchain-centos7
  commands:
  - ./autogen.sh
  - ./configure
  - make
- name: rpmbuild
  image: rpmbuild:el7
  spec: synbak.spec
